# Dependencies
markdown:         redcarpet
highlighter:      rb-pygments
plugins: [jekyll-gist, jekyll-paginate-v2]
repository:       pboueke/b
# Permalinks
permalink:        pretty
#relative_permalinks: true

gems:
  - jekyll-paginate-v2

# Setup
title:            pboueke
tagline:          'about'
description:      'My personal page. Here you may find some of my thoughts and experiences.'
url:              "https://pboueke.github.io"
baseurl:          "/b"

author:
  name:           'Pedro Boueke'
  url:            https://github.com/pboueke

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  tags:
      layouts:
        - 'posts.html'
      title: 'tag: ":tag"' # :tag is replaced by the tag name
      permalink: '/tag/:tag'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pboueke/pboueke.github.io
